### ISSUE TITLE
Question: Cubemaps support

### ISSUE THREAD

**Issue by NCrashed** [lambdacube3d/lambdacube-compiler#3]
Are cubemaps supported or planned at coming releases? I want to play with shadow maps for point lights and I don't actually know if manual implementation of cube map (by six 2D textures) is a good idea.

**Comment by csabahruska** [comment]
It's not supported yet, but it will be in the future releases indeed. Using 6 2D textures could be a good workaround.

**Comment by NCrashed** [comment]
Thank you!
