### ISSUE TITLE
Question: How to pass Lines into mesh?

### ISSUE THREAD

**Issue by NCrashed** [lambdacube3d/lambdacube-compiler#7]
Hi, I have stuck at wireframe mesh rendering, as I couldn't find 'P_Lines':

``` haskell
data MeshPrimitive
  = P_Points
  | P_TriangleStrip
  | P_Triangles
  | P_TriangleStripI (Vector Int32)
  | P_TrianglesI (Vector Int32)
  deriving (Show, Eq, Ord)
```

I know the workaround is to pass fake point across each line and render them as triangles, but I am curious if that mesh primitive is planned.

**Comment by csabahruska** [comment]
Hi,
The Mesh type is just for convenience.
As a workaround you use the lower level API. Here how it's done for Mesh:
[LambdaCube/GL/Mesh.hs](https://github.com/lambdacube3d/lambdacube-gl/blob/master/src/LambdaCube/GL/Mesh.hs#L50-L55)
[LambdaCube/GL/Type.hs](https://github.com/lambdacube3d/lambdacube-gl/blob/master/src/LambdaCube/GL/Type.hs#L431)
But if you're on GL33 for wireframed triangles just use [PolygonLine](http://lambdacube3d.com/api-documentation#rasterization-contexts) in rasterization context. But it does not work on GLES 2.0 or WebGL 1.0

**Comment by csabahruska** [comment]
Do you need Line Mesh primitives also? I can add it.

**Comment by NCrashed** [comment]
Thanks, I added fake third point and switched to `PolygonLine`. 

It was a debug code to render TrueType font contours.
